*** Variables ***
${home_locator.lbl_product_manage}    css=a.has-arrow.waves-effect.waves-dark:has-text("ระบบจัดสินค้า")
${home_locator.lbl_order_product}     css=a.sub-menu-link:has-text("สั่งจัดสินค้า")
${home_locator.lbl_order_jobs}        css=a.sub-menu-link:has-text("งานประจำวัน")
${home_locator.lbl_job_daily}         css=a.waves-effect.waves-dark.menu-link:has-text("งานจัดสินค้าประจำวัน")
${home_locator.lbl_reprint}           css=a.has-arrow.waves-effect.waves-dark:has-text("พิมพ์ซ้ำเอกสาร")
${home_locator.lbl_reprint_package_no}    css=a.sub-menu-link:has-text("พิมพ์ซ้ำใบปะหน้ากล่อง")
${home_locator.lbl_save_location}     css=a.waves-effect.waves-dark.menu-link:has-text("บันทึก Location")
${home_locator.lbl_customer_pickup}     css=a.waves-effect.waves-dark.menu-link:has-text("ส่งมอบสินค้าให้ลูกค้า")
${home_locator.lbl_scan_confrim_driver}    css=a.waves-effect.waves-dark.menu-link:has-text("ส่งมอบสินค้าให้ขนส่ง")
${home_locator.lbl_customerinfo}      css=a.waves-effect.waves-dark.menu-link:has-text("ตรวจสอบข้อมูลลูกค้า")
${home_locator.lbl_manage_delivery}    css=a.has-arrow.waves-effect.waves-dark:has-text("จัดการงานประจำวัน")
${home_locator.lbl_manage_routing}     css=a.sub-menu-link:has-text("จัดงานขนส่งสาขา")
${home_locator.lbl_confirm_truck}     css=a.sub-menu-link:has-text("ยืนยันรถขนส่งสาขา")
${home_locator.lbl_driver_receive_order}     css=a.waves-effect.waves-dark.menu-link:has-text("รับสินค้า")
${home_locator.lbl_driver_delivery_order}     css=a.waves-effect.waves-dark.menu-link:has-text("ส่งสินค้า")
${home_locator.lbl_report}    css=a.has-arrow.waves-effect.waves-dark:has-text("รายงาน")
${home_locator.lbl_daily_job_report}    css=a.sub-menu-link:has-text("รายงานการขนส่งสินค้า/บริการ")


