*** Variables ***
${receive_order_locator.txt_calendar}    css=#TextDateSearch
${receive_order_locator.btn_search_job}    css=#btSearchJob
${receive_order_locator.btn_prev_month}        css=.prev.available
${receive_order_locator.btn_next_month}        css=.prev.available~.month~.next.available
${receive_order_locator.lbl_month}           css=.prev.available~.month
${receive_order_locator.lbl_date_no}         css=div.calendar-table td.available:text-is("{day}"):visible
${receive_order_locator.lbl_job_card}        css=.ribbon.ribbon-info.ribbon-vertical-l~div .card-body
${receive_order_locator.btn_shopping_card}    css=.fas.fa-shopping-cart
${receive_order_locator.btn_task}        css=.fas.fa-tasks
${receive_order_locator.btn_store}        css=.mdi.mdi-store
${receive_order_locator.btn_camera}        css=.fas.fa-camera
${receive_order_locator.btn_truck_loading}        css=.timeline-badge.info .fas.fa-truck-loading
${receive_order_locator.btn_confirm_store_checkin}        css=#btnCheckInAtStore
${receive_order_locator.btn_upload_image}        css=.dz-hidden-input
${receive_order_locator.btn_confirm_upload_image}        css=#btnUploadImageAtStore
${receive_order_locator.btn_confirm_truck_loading}        css=.timeline-badge .fas.fa-truck-loading
${receive_order_locator.chk_select_package}    css=.iCheck-helper
${receive_order_locator.btn_next_step}    css=#btnNextStep
${receive_order_locator.btn_close_barcode_popup}    css=#btCloseModal
${receive_order_locator.img_qr_review}    css=#divQrReviewForLP img